/* Magazinolog — makale & kategori veri deposu */
window.MG_ARTICLES = {
  "rayli-sistem": {
    id: "rayli-sistem",
    title: "Büyükşehirlerde raylı sistem seferberliği: 11 hat için imzalar atıldı",
    category: "gundem",
    categoryLabel: "Gündem",
    image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=1400&q=75",
    date: "26 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 47,
    views: "1.284",
    excerpt: "Toplam 214 kilometrelik yeni güzergâh planı, kent içi ulaşımda özel araç kullanımını üçte bir oranında azaltmayı hedefliyor.",
    body: [
      "Büyükşehir belediyeleri ile ulaştırma idaresi arasında imzalanan protokol, 11 yeni raylı sistem hattının finansman ve yapım takvimini netleştirdi.",
      "Projelerin tamamı 2030 yılına kadar aşamalı olarak devreye alınacak. İlk etapta üç hattın ihale süreçlerinin bu yıl içinde tamamlanması bekleniyor.",
      "Uzmanlar, entegre aktarma noktalarının doğru planlanması halinde kent merkezindeki trafikte ölçülebilir bir rahatlama yaşanabileceğini belirtiyor."
    ]
  },
  "yenilenebilir": {
    id: "yenilenebilir",
    title: "Yenilenebilir üretim ilk kez toplam elektriğin yarısını karşıladı",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1400&q=75",
    date: "25 Temmuz 2026",
    author: "Selin Karaca",
    comments: 22,
    views: "963",
    excerpt: "Rüzgâr ve güneşteki kapasite artışı, yaz aylarındaki rekor talebe rağmen ithal yakıt faturasını geriletti.",
    body: [
      "Ulusal şebeke verilerine göre yenilenebilir kaynaklar ilk kez aylık elektrik üretiminin yüzde 50'sini aştı.",
      "Kurulu güçteki artış, özellikle öğle saatlerinde güneş üretiminin sistem dengesine katkısını görünür kıldı.",
      "Enerji piyasası düzenleyicisi, kapasite ödemeleri ve depolama yatırımlarının bir sonraki aşamada öne çıkacağını duyurdu."
    ]
  },
  "uydu": {
    id: "uydu",
    title: "Yerli haberleşme uydusu için fırlatma takvimi öne çekildi",
    category: "teknoloji",
    categoryLabel: "Teknoloji",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1400&q=75",
    date: "25 Temmuz 2026",
    author: "Emre Tunç",
    comments: 15,
    views: "771",
    excerpt: "Test süreçlerini planlanandan erken tamamlayan ekip, kırsal bölgelerde geniş bant erişimini iki katına çıkarmayı planlıyor.",
    body: [
      "Yerli haberleşme uydusunun fırlatma penceresi, tamamlanan yer testlerinin ardından üç ay öne alındı.",
      "Proje, özellikle düşük yoğunluklu yerleşimlerde internet erişimini güçlendirmeyi hedefliyor.",
      "Uzay ajansı, yörüngeye oturma sonrası ilk sinyal testlerinin 60 gün içinde paylaşılacağını açıkladı."
    ]
  },
  "ege-sezon": {
    id: "ege-sezon",
    title: "Ege kıyılarında sezon erken açıldı, doluluk yüzde 74'e ulaştı",
    category: "yasam",
    categoryLabel: "Seyahat",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=800&q=70",
    date: "26 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 18,
    views: "540",
    excerpt: "Erken rezervasyon kampanyaları ve iç turizm talebi, Ege'de sezonu öne çekti.",
    body: [
      "Turizm işletmeleri, haziran sonundan itibaren yüzde 74 doluluk oranına ulaştıklarını bildirdi.",
      "Yerel yönetimler, su ve atık yönetimi kapasitesini artıracak ek önlem paketini açıkladı."
    ]
  },
  "sakatlik-soku": {
    id: "sakatlik-soku",
    title: "Hazırlık kampında sakatlık şoku: iki oyuncu kadro dışı",
    category: "spor",
    categoryLabel: "Spor",
    image: "https://images.unsplash.com/photo-1508997449629-303059a039c0?auto=format&fit=crop&w=800&q=70",
    date: "26 Temmuz 2026",
    author: "Berk Aydın",
    comments: 31,
    views: "890",
    excerpt: "Sezon öncesi kampta yaşanan sakatlıklar teknik heyetin planlarını değiştirdi.",
    body: [
      "İki oyuncunun sezonun ilk haftalarını kaçırması bekleniyor.",
      "Kulüp, kadro derinliğini artırmak için kiralık seçenekleri de değerlendirdiğini duyurdu."
    ]
  },
  "tarifler": {
    id: "tarifler",
    title: "Anadolu'nun unutulan tarifleri kayıt altına alınıyor",
    category: "yasam",
    categoryLabel: "Lezzet",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=70",
    date: "24 Temmuz 2026",
    author: "Ayşe Duran",
    comments: 9,
    views: "412",
    excerpt: "Gastronomi arşivi projesi, yerel mutfak kültürünü dijital ortama taşıyor.",
    body: ["Tariflerin yanı sıra üretim teknikleri ve bölgesel ürün haritaları da belgeleniyor."]
  },
  "hibrit-ofis": {
    id: "hibrit-ofis",
    title: "Hibrit düzen kalıcılaşıyor: ofis talebi yüzde 12 düştü",
    category: "ekonomi",
    categoryLabel: "Çalışma",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=600&q=70",
    date: "23 Temmuz 2026",
    author: "Selin Karaca",
    comments: 12,
    views: "501",
    excerpt: "Şirketler ofis alanını küçültürken ortak çalışma alanlarına yöneliyor.",
    body: ["Gayrimenkul danışmanları, A sınıfı ofislerde yeniden planlama döneminin başladığını belirtiyor."]
  },
  "kent-orman": {
    id: "kent-orman",
    title: "Kent ormanları için 40 bin fidanlık yeni plan",
    category: "yasam",
    categoryLabel: "Çevre",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=70",
    date: "22 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 7,
    views: "330",
    excerpt: "Yeni yeşil kuşak projesi sıcak ada etkisini azaltmayı amaçlıyor.",
    body: ["İlk dikimler sonbahar döneminde başlayacak."]
  },
  "festival": {
    id: "festival",
    title: "Festival takvimi genişledi: 63 şehirde sahne kuruluyor",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=600&q=70",
    date: "21 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 16,
    views: "620",
    excerpt: "Yaz kültür programı bu yıl rekor sayıda ile yayılıyor.",
    body: ["Açık hava konserleri ve yerel sanatçı vitrinleri programın omurgasını oluşturuyor."]
  },
  "stadyum": {
    id: "stadyum",
    title: "Yeni stadyumlarda seyirci kapasitesi yüzde 30 artıyor",
    category: "spor",
    categoryLabel: "Spor",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Berk Aydın",
    comments: 23,
    views: "710",
    excerpt: "Yenileme projeleri tribün konforunu ve güvenlik standartlarını yükseltiyor.",
    body: ["İlk etap tesislerin yeni sezonda hizmete girmesi planlanıyor."]
  },
  "akdeniz-mutfak": {
    id: "akdeniz-mutfak",
    title: "Akdeniz mutfağı üzerine on yıllık takip çalışması sonuçlandı",
    category: "saglik",
    categoryLabel: "Sağlık",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Dr. Ayşe Duran",
    comments: 11,
    views: "455",
    excerpt: "Uzun dönemli beslenme araştırması kalp sağlığı göstergelerinde iyileşme raporladı.",
    body: ["Araştırmacılar, zeytinyağı ve sebze ağırlıklı diyetin sürdürülebilir etkisine dikkat çekti."]
  },
  "basket-yayin": {
    id: "basket-yayin",
    title: "Basketbol liginde yayın hakları rekor bedelle satıldı",
    category: "spor",
    categoryLabel: "Spor",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=700&q=70",
    date: "25 Temmuz 2026",
    author: "Berk Aydın",
    comments: 8,
    views: "388",
    excerpt: "Yeni anlaşma ligin dijital yayın gelirlerini de kapsıyor.",
    body: ["Kulüpler gelir paylaşım modelinin güncellenmesini bekliyor."]
  },
  "tarim-fon": {
    id: "tarim-fon",
    title: "Erken aşama fonlar tarım teknolojilerine yöneldi",
    category: "ekonomi",
    categoryLabel: "Girişim",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=700&q=70",
    date: "25 Temmuz 2026",
    author: "Selin Karaca",
    comments: 14,
    views: "502",
    excerpt: "Agri-tech girişimleri son çeyrekte yatırım turlarında öne çıktı.",
    body: ["Sensör, sulama otomasyonu ve izlenebilirlik çözümleri yatırımcıların radarında."]
  },
  "iklim-fon": {
    id: "iklim-fon",
    title: "İklim zirvesinde ortak fon için uzlaşma sağlandı",
    category: "dunya",
    categoryLabel: "Dünya",
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=800&q=70",
    date: "26 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 19,
    views: "640",
    excerpt: "Gelişmekte olan ülkeler için yeni iklim finansmanı paketinde mutabakat oluştu.",
    body: ["Fonun ilk diliminin 2027 başında serbest bırakılması öngörülüyor."]
  },
  "tedarik": {
    id: "tedarik",
    title: "Tedarik zincirinde rota değişimi: yeni koridor devrede",
    category: "dunya",
    categoryLabel: "Dünya",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=70",
    date: "25 Temmuz 2026",
    author: "Emre Tunç",
    comments: 27,
    views: "812",
    excerpt: "Küresel lojistik şirketleri alternatif koridorlara yöneliyor.",
    body: ["Transit sürelerinin kısaltılması maliyet baskısını hafifletebilir."]
  },
  "secim-takvim": {
    id: "secim-takvim",
    title: "Avrupa'da yerel seçim takvimi netleşti, kampanyalar başladı",
    category: "dunya",
    categoryLabel: "Dünya",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=300&q=70",
    date: "25 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 6,
    views: "290",
    excerpt: "Birçok ülkede yerel seçim takvimleri ardışık haftalara yayıldı.",
    body: ["Kampanya finansmanı ve dijital reklam kuralları yeniden tartışılıyor."]
  },
  "kuraklik": {
    id: "kuraklik",
    title: "Akdeniz havzasında kuraklık haritası yeniden çizildi",
    category: "dunya",
    categoryLabel: "Dünya",
    image: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=300&q=70",
    date: "24 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 10,
    views: "360",
    excerpt: "Yeni uydu verileri risk bölgelerini güncelledi.",
    body: ["Tarım ve su yönetimi kurumları acil eylem planlarını paylaştı."]
  },
  "kira-sinir": {
    id: "kira-sinir",
    title: "Büyük şehirlerde kira artışına yeni üst sınır tartışması",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=300&q=70",
    date: "24 Temmuz 2026",
    author: "Selin Karaca",
    comments: 21,
    views: "680",
    excerpt: "Konut piyasasında düzenleme arayışları hız kazandı.",
    body: ["Sektör temsilcileri arz artışı olmadan tavanın yetersiz kalacağını savunuyor."]
  },
  "liman": {
    id: "liman",
    title: "Liman yatırımlarında konteyner kapasitesi ikiye katlanıyor",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1473445730015-841f29a9490b?auto=format&fit=crop&w=300&q=70",
    date: "23 Temmuz 2026",
    author: "Emre Tunç",
    comments: 5,
    views: "275",
    excerpt: "Yeni rıhtım ve vinç yatırımları ihracat kapasitesini destekleyecek.",
    body: ["İlk fazın 18 ay içinde tamamlanması hedefleniyor."]
  },
  "yayla-rota": {
    id: "yayla-rota",
    title: "Yaylalarda 12 yeni yürüyüş rotası",
    category: "yasam",
    categoryLabel: "Seyahat",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 4,
    views: "210",
    excerpt: "Doğa turizmi için işaretli parkurlarda güvenlik önlemleri artırıldı.",
    body: ["Rotların haritaları mobil uygulamada da yayınlandı."]
  },
  "mavi-bayrak": {
    id: "mavi-bayrak",
    title: "Mavi bayrak sayısı 41 plajda arttı",
    category: "yasam",
    categoryLabel: "Seyahat",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=70",
    date: "25 Temmuz 2026",
    author: "Ayşe Duran",
    comments: 3,
    views: "198",
    excerpt: "Su kalitesi ve hizmet standartları denetimlerden geçti.",
    body: ["Yeni bayraklı plajlar listesi turizm portallarında güncellendi."]
  },
  "sakin-sehir": {
    id: "sakin-sehir",
    title: "Sakin şehirlerde yaz nüfusu rekoru",
    category: "yasam",
    categoryLabel: "Yaşam",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=700&q=70",
    date: "24 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 8,
    views: "340",
    excerpt: "Küçük sahil kasabaları sezonluk nüfus baskısıyla karşı karşıya.",
    body: ["Belediyeler altyapı yatırımlarını öne çekiyor."]
  },
  "kooperatif": {
    id: "kooperatif",
    title: "Mahalle kooperatifleri yeniden canlanıyor: 300 yeni girişim",
    category: "yasam",
    categoryLabel: "Yaşam",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=70",
    date: "26 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 12,
    views: "470",
    excerpt: "Yerel üretim ve paylaşım ağları mahalle ölçeğinde güçleniyor.",
    body: ["Destek paketleri eğitim ve mikro kredi bileşenlerini bir araya getiriyor."]
  },
  "sinema-fon": {
    id: "sinema-fon",
    title: "Bağımsız sinemaya destek fonu üç kat büyüdü",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=300&q=70",
    date: "26 Temmuz 2026",
    author: "Emre Tunç",
    comments: 9,
    views: "305",
    excerpt: "Yeni dönem başvuru takvimi açıklandı.",
    body: ["Kısa film ve belgesel kategorilerinde kontenjan artırıldı."]
  },
  "gece-kutuphane": {
    id: "gece-kutuphane",
    title: "Gece kütüphaneleri projesi 24 ilde uygulanacak",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=300&q=70",
    date: "25 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 11,
    views: "390",
    excerpt: "Öğrenci yoğun bölgelerde 7/24 çalışma alanları yaygınlaşıyor.",
    body: ["Pilot illerdeki kullanım verileri talebi doğruladı."]
  },
  "konser": {
    id: "konser",
    title: "Açık hava konserlerinde bilet satışları ikiye katlandı",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=300&q=70",
    date: "24 Temmuz 2026",
    author: "Berk Aydın",
    comments: 13,
    views: "520",
    excerpt: "Yaz konser ekonomisi rekor ciroya koşuyor.",
    body: ["Organizatörler güvenlik ve ulaşım planlarını güçlendirdi."]
  },
  "sanat-atolye": {
    id: "sanat-atolye",
    title: "Çağdaş sanat atölyeleri üniversite kampüslerine taşınıyor",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=300&q=70",
    date: "23 Temmuz 2026",
    author: "Emre Tunç",
    comments: 6,
    views: "240",
    excerpt: "Kampüs-sanat iş birlikleri yeni üretim alanları açıyor.",
    body: ["Öğrenci ve sanatçı ortak üretim programları sonbaharda başlıyor."]
  },
  "dijital-kamu": {
    id: "dijital-kamu",
    title: "Dijital kamu hizmetlerinde tek pencere dönemi başlıyor",
    category: "teknoloji",
    categoryLabel: "Teknoloji",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=70",
    date: "26 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 23,
    views: "800",
    excerpt: "Vatandaş işlemleri tek kimlik doğrulama ile birleştiriliyor.",
    body: ["Geçiş süreci aşamalı olacak; kritik hizmetlerde paralel sistem sürecek."]
  },
  "video-randevu": {
    id: "video-randevu",
    title: "Hastanelerde randevu sistemi nasıl değişti?",
    category: "video",
    categoryLabel: "Video",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Magazinolog Video",
    comments: 17,
    views: "1.100",
    excerpt: "Yeni randevu algoritması bekleme sürelerini kısaltmayı hedefliyor.",
    body: ["Video haberde saha röportajları ve ekran kayıtları yer alıyor."]
  },
  "muze-ucretsiz": {
    id: "muze-ucretsiz",
    title: "Kent müzelerinde ücretsiz giriş uygulaması genişliyor",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 23,
    views: "560",
    excerpt: "Pilot uygulamanın ardından 18 müzede daha hafta içi ziyaretler ücretsiz hâle geliyor.",
    body: ["Ziyaretçi sayısında ilk artış kaydedildi; rehberli tur kontenjanları da artırıldı."]
  },
  "balikcilik": {
    id: "balikcilik",
    title: "Balıkçılık sezonu öncesi kota düzenlemesi yürürlükte",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1520333789090-1afc82db536a?auto=format&fit=crop&w=700&q=70",
    date: "26 Temmuz 2026",
    author: "Emre Tunç",
    comments: 9,
    views: "310",
    excerpt: "Stokların korunması amacıyla belirlenen yeni av kotaları yürürlüğe girdi.",
    body: ["Küçük ölçekli teknelere ek destek paketi de duyuruldu."]
  },
  "serbest-calisma": {
    id: "serbest-calisma",
    title: "Serbest çalışma alanları küçük şehirlere yayılıyor",
    category: "teknoloji",
    categoryLabel: "Teknoloji",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=700&q=70",
    date: "25 Temmuz 2026",
    author: "Selin Karaca",
    comments: 16,
    views: "440",
    excerpt: "Kira avantajı ve fiber altyapı yatırımları ortak çalışma alanı sayısını artırdı.",
    body: ["Yerel girişimcilik ekosistemleri yeni hub'larla güçleniyor."]
  },
  "egitim-takvim": {
    id: "egitim-takvim",
    title: "Yeni eğitim yılı takvimi açıklandı, ders saatleri güncellendi",
    category: "yasam",
    categoryLabel: "Eğitim",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=700&q=70",
    date: "25 Temmuz 2026",
    author: "Deniz Aksoy",
    comments: 34,
    views: "920",
    excerpt: "Sıcak hava koşulları nedeniyle bazı bölgelerde başlangıç tarihi ertelendi.",
    body: ["Telafi planı ve esnek mesai seçenekleri paylaşıldı."]
  },
  "ihracat-paket": {
    id: "ihracat-paket",
    title: "İhracatçı firmalar için yeni finansman paketi devrede",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=700&q=70",
    date: "24 Temmuz 2026",
    author: "Selin Karaca",
    comments: 12,
    views: "480",
    excerpt: "Paket, orta ölçekli üreticilerin döviz kazandırıcı işlemlerinde maliyetleri düşürmeyi hedefliyor.",
    body: ["Başvurular dijital portal üzerinden alınacak."]
  },
  "sokak-hayvan": {
    id: "sokak-hayvan",
    title: "Belediyelerden sokak hayvanları için ortak bakım ağı",
    category: "yasam",
    categoryLabel: "Yaşam",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=700&q=70",
    date: "24 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 27,
    views: "650",
    excerpt: "Yedi ilçenin katıldığı protokolle kısırlaştırma ve barınak kapasitesi ortak yönetilecek.",
    body: ["Gönüllü ağları ile belediye ekipleri eşgüdümlü çalışacak."]
  },
  "e-spor": {
    id: "e-spor",
    title: "Ulusal e-spor liginde seyirci rekoru kırıldı",
    category: "spor",
    categoryLabel: "Spor",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=700&q=70",
    date: "22 Temmuz 2026",
    author: "Berk Aydın",
    comments: 19,
    views: "730",
    excerpt: "Final haftası hem salonda hem çevrim içi rekor izlenme getirdi.",
    body: ["Sponsor gelirleri geçen yıla göre ikiye katlandı."]
  },
  "yapay-zeka": {
    id: "yapay-zeka",
    title: "Kamu arşivlerinde yapay zekâ ile sınıflandırma dönemi",
    category: "teknoloji",
    categoryLabel: "Teknoloji",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=700&q=70",
    date: "21 Temmuz 2026",
    author: "Emre Tunç",
    comments: 14,
    views: "510",
    excerpt: "Milyonlarca belgenin otomatik etiketlemesi başladı.",
    body: ["İnsan denetimli doğrulama katmanı süreçte korunuyor."]
  },
  "asistan-saglik": {
    id: "asistan-saglik",
    title: "Aile hekimliğinde dijital asistan pilotu genişliyor",
    category: "saglik",
    categoryLabel: "Sağlık",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=700&q=70",
    date: "20 Temmuz 2026",
    author: "Dr. Ayşe Duran",
    comments: 8,
    views: "290",
    excerpt: "Randevu hatırlatma ve ilaç takibi için yeni araçlar devrede.",
    body: ["Pilot illerde hasta memnuniyeti anketleri olumlu seyrediyor."]
  },
  "karbon-borsa": {
    id: "karbon-borsa",
    title: "Karbon piyasasında işlem hacmi yeni zirveye çıktı",
    category: "ekonomi",
    categoryLabel: "Ekonomi",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=700&q=70",
    date: "19 Temmuz 2026",
    author: "Selin Karaca",
    comments: 7,
    views: "360",
    excerpt: "Şirketlerin gönüllü karbon kredisi alımları hızlandı.",
    body: ["Düzenleyici çerçeve taslağı sonbaharda görüşülecek."]
  },
  "muzik-arsiv": {
    id: "muzik-arsiv",
    title: "Anadolu ezgileri dijital arşivde yeniden hayat buluyor",
    category: "kultur",
    categoryLabel: "Kültür",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=700&q=70",
    date: "18 Temmuz 2026",
    author: "Nil Erdoğan",
    comments: 5,
    views: "220",
    excerpt: "Nadir kayıtlar restore edilerek açık erişime açılıyor.",
    body: ["Proje üniversiteler ve yerel radyo arşivleriyle ortak yürütülüyor."]
  }
};

window.MG_CATEGORIES = {
  dunya: { slug: "dunya", name: "Dünya", accent: "sky", ids: ["iklim-fon", "tedarik", "secim-takvim", "kuraklik", "kira-sinir", "liman"] },
  ekonomi: { slug: "ekonomi", name: "Ekonomi", accent: "emerald", ids: ["yenilenebilir", "hibrit-ofis", "tarim-fon", "kira-sinir", "liman", "balikcilik", "ihracat-paket", "karbon-borsa"] },
  teknoloji: { slug: "teknoloji", name: "Teknoloji", accent: "amber", ids: ["uydu", "dijital-kamu", "serbest-calisma", "yapay-zeka"] },
  yasam: { slug: "yasam", name: "Yaşam", accent: "fuchsia", ids: ["ege-sezon", "tarifler", "kent-orman", "kooperatif", "yayla-rota", "mavi-bayrak", "sakin-sehir", "egitim-takvim", "sokak-hayvan"] },
  video: { slug: "video", name: "Video", accent: "violet", ids: ["video-randevu", "akdeniz-mutfak", "tarifler", "tarim-fon", "stadyum", "e-spor", "dijital-kamu", "yapay-zeka"] },
  spor: { slug: "spor", name: "Spor", accent: "rose", ids: ["sakatlik-soku", "stadyum", "basket-yayin", "e-spor"] },
  saglik: { slug: "saglik", name: "Sağlık", accent: "teal", ids: ["akdeniz-mutfak", "asistan-saglik"] },
  kultur: { slug: "kultur", name: "Kültür", accent: "orange", ids: ["festival", "sinema-fon", "gece-kutuphane", "konser", "sanat-atolye", "muze-ucretsiz", "muzik-arsiv"] },
  gundem: { slug: "gundem", name: "Gündem", accent: "brand", ids: ["rayli-sistem"] }
};

window.MG_HOME_CATEGORIES = ["dunya", "ekonomi", "teknoloji", "yasam", "spor", "kultur"];
